Increase the versatility of scripts
rm-controls/rm_bringup pull request #22
Opened 2023-05-26 18:07 UTC by ye-luo-xi-tui

- 增加start_master.sh和rm_start.sh两个脚本的通用性。、
- 增加environment.sh脚本，在部署时需修改该脚本内的环境变量，并将此脚本复制到机器人机载pc的家目录下。
- 在给机器人部署程序时永远不会修改start_master.sh和rm_start.sh

2023-05-26 18:17 UTC, ye-luo-xi-tui commented
ddl 5.27

2023-05-26 18:26 UTC, Edwinlinks approved these changes

2023-05-27 14:28 UTC, qiayuanliao requested changes
做得很好，质量高且速度快。

根据我的comment小修改一下，即可全面部署在步兵和英雄上。

然后再看看工程有没有救hhh。

2023-05-27 14:28 UTC, qiayuanliao commented on scripts/auto_start/rm_start.sh
>  export ROS_PACKAGE_PATH=~/rm_ws:$ROS_PACKAGE_PATH
这句是不需要的，可能是我以前对工作空间没有理解透写的。

2023-05-27 14:28 UTC, qiayuanliao commented on scripts/auto_start/rm_start.sh
>  source ~/rm_ws/devel/setup.bash
这个对于平衡步兵来说不一样。

2023-05-27 14:28 UTC, qiayuanliao commented on scripts/auto_start/rm_start.sh
> +mon launch --disable-ui rm_bringup $LAUNCH.launch
有时候后面会加入选项如晨辉的电脑里面的 rm_start.sh：

`mon launch --disable-ui rm_bringup start.launch balance:=true
`

2023-05-27 14:28 UTC, qiayuanliao commented on scripts/auto_start/environment.sh
> +# ...
每台车都有一个它的名字命名的环境变量文件，**做版本管理**。

并实现以下功能：

部署 rm_start.sh  时（运行“创建服务和复制rm_start.sh 到用户根目录”的脚本时），可以输入robot type，自动拷贝对应名字的环境变量文件到用户根目录并重命名为"environment.sh"

2023-05-27 14:28 UTC, qiayuanliao commented on scripts/auto_start/rm_start.sh
> +mon launch --disable-ui rm_bringup $LAUNCH.launch
不过平衡步兵可以另外写一个launch @chenhuiYu00

2023-05-27 17:54 UTC, ye-luo-xi-tui commented on scripts/auto_start/rm_start.sh
>  export ROS_PACKAGE_PATH=~/rm_ws:$ROS_PACKAGE_PATH
> 这句是不需要的，可能是我以前对工作空间没有理解透写的。

已删除

2023-05-27 17:55 UTC, ye-luo-xi-tui commented on scripts/auto_start/rm_start.sh
>  source ~/rm_ws/devel/setup.bash
> 这个对于平衡步兵来说不一样。

多source了平衡步兵需要的环境变量

2023-05-27 17:55 UTC, ye-luo-xi-tui commented on scripts/auto_start/rm_start.sh
> +mon launch --disable-ui rm_bringup $LAUNCH.launch
> 不过平衡步兵可以另外写一个launch @chenhuiYu00

跟晨辉说了让他单独给平衡步兵搞个launch

2023-05-27 17:59 UTC, ye-luo-xi-tui commented on scripts/auto_start/environment.sh
> +# ...
> 每台车都有一个它的名字命名的环境变量文件，**做版本管理**。
> 
> 并实现以下功能：
> 
> 部署 rm_start.sh 时（运行“创建服务和复制rm_start.sh 到用户根目录”的脚本时），可以输入robot type，自动拷贝对应名字的环境变量文件到用户根目录并重命名为"environment.sh"

先加了standard3和standard4，放在envionment文件夹下，其他车在部署时再添加与pr。
目前创建服务的脚本已经是通用的（输入服务名），改这个脚本来实现预期功能并不方便。新加了deploy.sh脚本来做这件事。

2023-05-28 02:20 UTC, qiayuanliao approved these changes
很好~质量高，速度快！！！

2023-05-29 07:02 UTC, merged