Add control topics rosbag record and modify something.
rm-controls/rm_bringup pull request #7
Opened 2022-07-12 09:08 UTC by LHTcode

2022-07-15 02:12 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-07-15 09:40 UTC, qiayuanliao requested changes
- 还是得找运维的老哥review一下，我本身不太懂bash
- create 和 delete 需要写成通用的，每个服务的create和delete操作都是一模一样的、运行脚本时。要求用户输入要 create 或 delete 哪个“开机自启服务”即可~

2022-07-15 09:40 UTC, qiayuanliao commented on scripts/auto_start/control_rosbag_record_service.sh
> +                rosbag record -q -b 2048 --duration=300 -O "$FILEINDEX"  "/actuator_states" "/cmd_vel" "/controllers/chassis_controller/command" "/controllers/chassis_controller/left_back/command" "/
不应该如此指定要录的topic，太傻了

2022-07-16 02:34 UTC, qiayuanliao approved these changes

2022-07-18 16:05 UTC, YuuinIH commented
lgtm

2022-07-20 06:27 UTC, YuuinIH commented on scripts/auto_start/control_rosbag_record_service.sh
> +                rosbag record -q -b 2048 --duration=300 -O "$FILEINDEX"  "/actuator_states" "/cmd_vel" "/controllers/chassis_controller/command" "/controllers/chassis_controller/left_back/command" "/
topic可以分开一个变量……
这么写太怪了

2022-07-20 06:29 UTC, YuuinIH commented
lgtm

2022-07-20 07:24 UTC, qiayuanliao commented
@ye-luo-xi-tui 加一下rules

2022-07-22 12:29 UTC, ye-luo-xi-tui commented on scripts/auto_start/create_specific_service.sh
> +done
重复代码是不推崇的。将脚本文件复制到家目录和系统目录放在一起做就好了。

2022-07-22 12:37 UTC, ye-luo-xi-tui commented on scripts/auto_start/create_specific_service.sh
> +done
这个enable也可以和上面的循环放在一起，需要echo的提示信息也一起放在循环里面，使能多个服务时每个服务都echo一次提示信息。

2022-07-23 02:02 UTC, ye-luo-xi-tui commented on scripts/auto_start/create_specific_service.sh
> +done
@LHTcode

2022-07-23 02:09 UTC, LHTcode commented on scripts/auto_start/create_specific_service.sh
> +done
okok，这就改

2022-07-23 08:30 UTC, ye-luo-xi-tui commented
@YuuinIH 师兄帮忙review一下最新commit，是一个自动创建系统服务的脚本

2022-07-23 08:58 UTC, YuuinIH reviewed
看起来还行

2022-07-23 09:00 UTC, YuuinIH approved these changes

2022-07-24 12:12 UTC, merged