Update engineer's bringup and add auto_set_gpio
rm-controls/rm_bringup pull request #8
Opened 2022-07-27 08:08 UTC by ljq-lv

2022-07-27 08:13 UTC, ye-luo-xi-tui approved these changes

2022-07-27 08:13 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-07-28 07:28 UTC, qiayuanliao requested changes

2022-07-28 07:28 UTC, qiayuanliao commented on scripts/auto_start/auto_set_gpio.sh
> +sudo chmod 777 /sys/class/gpio/gpio663/value
???

2022-07-28 07:29 UTC, qiayuanliao commented on scripts/auto_start/auto_set_gpio.sh
> +sudo chmod 777 /sys/class/gpio/gpio663/value
@ye-luo-xi-tui 这你也能 approve？

2022-07-28 07:30 UTC, qiayuanliao commented on scripts/auto_start/auto_set_gpio.sh
> +sudo chmod 777 /sys/class/gpio/gpio663/value
@ljq-lv 你搁这恶心谁呢？脚本不会写可以问一下运维啊

2022-07-28 11:34 UTC, YuuinIH reviewed
简单看了一下

2022-07-28 11:34 UTC, YuuinIH commented on scripts/auto_start/auto_set_gpio.sh
> +sudo chmod 777 /sys/class/gpio/gpio663/value
这个写引脚的操作有点过于暴力了
我建议把引脚编号放在一个数组里 然后用一个for循环遍历

2022-07-28 11:34 UTC, YuuinIH commented on scripts/auto_start/auto_set_gpio.sh
> +while true
这里为啥要while True……

2022-07-28 12:19 UTC, YuuinIH approved these changes

2022-07-29 14:04 UTC, ye-luo-xi-tui commented
@qiayuanliao

2022-07-31 05:33 UTC, qiayuanliao approved these changes

2022-07-31 05:33 UTC, merged